services:

  ass-api-task:
    container_name: ass-api-task  # 命名規格 -> ass/bonus - api - 專案
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 9051:80                   # ass從9051開始
  
  # mysql_db:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: taravel_docker
  #   ports:
  #   - 3306:3306
  
  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   ports:
  #     - 9001:80
  #   environment:
  #     - PMA_ARBITRARY=1